import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "./providers"; // 1. Import your providers file
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning // 2. Add this to prevent browser hydration mismatches
    >
      {/* 3. Add global Hero UI utility classes to the body so background/text switch themes automatically */}
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <Providers>
          <Suspense
            fallback={
              <div className="h-20 w-full bg-background animate-pulse" />
            }
          >
            <Navbar />
          </Suspense>
          <main className="flex-1">{children}</main>
          <Footer />
          <Toaster position="bottom-center" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
